# -*- coding: utf-8 -*-
"""data_processing.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OX2Lyi9t6SZWomsG9N3fP0aoetGZbA9k
"""

print("adding all the data processing code related to fraud detection")